name: CosmeticMenu
main: NinjaKnights\CosmeticMenu\Main
version: 2.1
api: 3.13.0
author: TheKnightGamer / Jean
description: A CosmeticMenu plugin for server lobbys!
    
commands:
  cosmetics:
    description: "CosmeticMenu Command"